ci: Add integration tests
clearcontainers/agent pull request #60
Opened 2017-07-24 17:53 UTC by jcvenegas

Add scripts to run integration test in semaphoreci.

`./.ci/setup.sh` : Install clear containers using clearcontainers/tests setup script
`./.ci/run.sh`   : Build and install agent then run integration test

Fixes: #55

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

2017-07-25 09:19 UTC, grahamwhaley commented
Travis looks happy to me...
lgtm

2017-07-25 15:20 UTC, sboeuf requested changes
Several comments. I think that we could move most of the code in run.sh to setup.sh. Actually, the "real" thing that we are running is `make check` from tests repo, therefore I think this should be the only thing in this file.

2017-07-25 15:20 UTC, sboeuf commented on .ci/setup.sh
> +go get -d github.com/clearcontainers/runtime
Make github.com/clearcontainers/runtime a variable as you reuse it later in this script.

2017-07-25 15:20 UTC, sboeuf commented on .ci/setup.sh
> +pushd
You need `popd` here, not `pushd`.

2017-07-25 15:20 UTC, sboeuf commented on .ci/setup.sh
> +make
Remove this since the agent is built later in this script.

2017-07-25 15:20 UTC, sboeuf commented on .ci/setup.sh
> +cd go get -d ${github_project} || true
You should add a comment about this line. All it does is making sure we have the package dependencies this project needs to be built. Indeed, the agent repo is already on the Semaphore system at the commit version we want to test.
Note this won't move the commit version (which is what we want).

2017-07-25 15:20 UTC, sboeuf commented on .ci/setup.sh
> +make
For performance savings, let's use make -j$(nproc)

2017-07-25 15:20 UTC, sboeuf commented on .ci/setup.sh
> +cd go get -d ${github_project} || true
Oh and replace your command here:
s/cd go get -d ${github_project} || true/go get -d ${github_project} || true/
You've added one `cd` that we don't need.

2017-07-25 15:20 UTC, sboeuf commented on .ci/setup.sh
> +cd ${project_dir}
Use `pushd` to be consistent with the rest of this script.
And don't forget `popd` at the end of this block.

2017-07-25 15:20 UTC, sboeuf commented on .ci/setup.sh
> +sudo -E PATH=$PATH bash .ci/setup.sh
Usually we use `sudo -E PATH=$PATH bash -c ".ci/setup.sh"`

2017-07-25 15:20 UTC, sboeuf commented on .ci/run.sh
> +sudo mount "${loop}p1" "${MOUNT_DIR}"
You can replace those 3 last lines with:
```bash
sudo mount -o loop,offset=$((2048 * 512)) clear-${clr_release}-containers.img ${MOUNT_DIR}
```

2017-07-25 15:20 UTC, sboeuf commented on .ci/run.sh
> +make
No need to build, you already did that in setup.sh.

2017-07-25 15:20 UTC, sboeuf commented on .ci/run.sh
> +export DESTDIR=${MOUNT_DIR}
I don't think we need to export this one.

2017-07-25 15:20 UTC, sboeuf commented on .ci/run.sh
> +sudo make install DESTDIR=${MOUNT_DIR}
Replace with:
```bash
sudo -E PATH=$PATH bash -c "make install DESTDIR=${MOUNT_DIR}"
```

2017-07-25 15:20 UTC, sboeuf commented on .ci/run.sh
> +sudo losetup -d "${loop}"
No need for this line if you replaced the mount with the line I gave you.

2017-07-25 15:20 UTC, sboeuf commented on .ci/run.sh
> +sudo -E PATH=$PATH make check
Replace with:
```bash
sudo -E PATH=$PATH bash -c "make check"
```

2017-07-25 16:38 UTC, jcvenegas commented on .ci/setup.sh
> +go get -d github.com/clearcontainers/runtime
done

2017-07-25 16:38 UTC, jcvenegas commented on .ci/setup.sh
> +pushd
done

2017-07-25 16:38 UTC, jcvenegas commented on .ci/setup.sh
> +make
done

2017-07-25 16:38 UTC, jcvenegas commented on .ci/setup.sh
> +cd go get -d ${github_project} || true
done, done

2017-07-25 16:39 UTC, jcvenegas commented on .ci/setup.sh
> +cd ${project_dir}
done

2017-07-25 16:39 UTC, jcvenegas commented on .ci/setup.sh
> +make
done

2017-07-25 16:39 UTC, jcvenegas commented on .ci/setup.sh
> +sudo -E PATH=$PATH bash .ci/setup.sh
done

2017-07-25 16:39 UTC, jcvenegas commented on .ci/run.sh
> +sudo mount "${loop}p1" "${MOUNT_DIR}"
I dont think is good idea rely on a offset that should be calculated.

2017-07-25 16:40 UTC, jcvenegas commented on .ci/run.sh
> +make
done

2017-07-25 16:40 UTC, jcvenegas commented on .ci/run.sh
> +export DESTDIR=${MOUNT_DIR}
right!  export removed!

2017-07-25 16:40 UTC, jcvenegas commented on .ci/run.sh
> +sudo make install DESTDIR=${MOUNT_DIR}
changed :)

2017-07-25 16:41 UTC, jcvenegas commented on .ci/run.sh
> +sudo -E PATH=$PATH make check
done

2017-07-25 18:14 UTC, jcvenegas commented on .ci/setup.sh
> +go get -d github.com/clearcontainers/runtime
ups, just created the var, but did not used , fixing

2017-07-26 05:47 UTC, sboeuf approved these changes

2017-07-26 05:47 UTC, merged